Stop providing author inherent data
PureStake/nimbus pull request #31
Opened 2021-12-08 08:36 UTC by JoshOrndorff

DO NOT MERGE until after nimbus 0.9 has been tagged.

This PR is a followup to #15. It simplifies the client-side code by no longer providing any real inherent data. Previously it provided the author id, but since #15, the data supplied there has not been used, and the pre-runtime digest is used instead.

2021-12-08 12:56 UTC, librelois requested changes

2021-12-08 12:56 UTC, librelois commented on parachain-template/node/src/service.rs
>  						Ok((time, parachain_inherent, author))
```suggestion
						Ok((time, parachain_inherent))
```

2021-12-08 12:56 UTC, librelois commented on parachain-template/node/src/service.rs
> +						let author = nimbus_primitives::InherentDataProvider;
```suggestion

```

2021-12-13 14:48 UTC, librelois approved these changes

2022-04-04 17:58 UTC, JoshOrndorff commented
@librelois @nbaztec I believe this one is ready. Is there anything blocking it that you know of?

2022-04-04 19:11 UTC, librelois commented
@JoshOrndorff yes we can merge this PR now, we just forgot because we were constantly busy with other things!

2022-04-04 19:11 UTC, merged